[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "pip install -r backend/requirements.txt",
  "pip install -r bot/requirements.txt"
]

[start]
cmd = "sh -c \"uvicorn backend.main:app --host 0.0.0.0 --port $PORT --workers 1 & python -m bot.bot && wait\""
